# Generated by Django 6.0.1 on 2026-03-17 02:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('descripcion_breve', models.CharField(max_length=200, verbose_name='Descripción Breve')),
                ('descripcion_detallada', ckeditor.fields.RichTextField(verbose_name='Descripción Detallada')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios_img/', verbose_name='Imagen Promocional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('organizacion', models.CharField(max_length=150, verbose_name='Organización/Proyecto')),
                ('detalles_solicitud', models.TextField(verbose_name='Detalles de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('servicio_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.servicio', verbose_name='Servicio de Interés')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
