# Generated by Django 6.0.1 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Problema')),
                ('descripcion', models.TextField(verbose_name='Descripción o Detalles')),
                ('votos', models.IntegerField(default=0, verbose_name='Cantidad de Votos')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
            ],
            options={
                'verbose_name': 'Reporte de Problema',
                'verbose_name_plural': 'Reportes Ciudadanos',
                'ordering': ['-votos', '-fecha_reporte'],
            },
        ),
    ]
