# Generated by Django 6.0.1 on 2026-02-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_alter_alumnos_options'),
        ('Registros', '0002_alter_alumnos_options_alumnos_imagen_and_more'),
    ]

    operations = [
    ]
