# Generated by Django 6.0.1 on 2026-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Inscripción')),
                ('es_presencial', models.BooleanField(default=True, verbose_name='¿Es presencial?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos_img/', verbose_name='Imagen Promocional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
