# Generated by Django 6.0.1 on 2026-03-02 18:40

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_actividad', models.CharField(max_length=50, verbose_name='Clave de la Actividad')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción de la Actividad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.curso', verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
